# Generated by Django 4.2 on 2023-05-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_billing_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='transaction',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images'),
        ),
    ]
