# Generated by Django 4.2 on 2023-05-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_billing_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='transaction1',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
