# Generated by Django 4.2 on 2023-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_billing_transaction1'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='pcategory',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='pname',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='pprice',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
